name: ROS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    # env:
    steps:

      - name: git clone git@github.com:lucasw/chrono
        uses: actions/checkout@v2
        with:
          path: chrono
          submodules: true

      - name: install dependencies
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y dpkg
            sudo apt-get install -y libglfw3-dev
            sudo apt-get install -y libglm-dev
            sudo apt-get install -y libirrlicht-dev
            sudo apt-get install -y libxxf86vm-dev
            sudo apt-get install -y swig

      - name: make install dir
        run: |
          mkdir -p $HOME/other/install

      - name: build blaze
        run: |
          git clone https://bitbucket.org/blaze-lib/blaze.git
          mkdir -p build/blaze
          cd build/blaze
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/other/install ../../blaze/
          make
          make install
          ls -l $HOME/other/install

      - name: compress output
        run: |
          # Trying to upload the dir results in error, so tar it up
          # Warning: No files were found with the provided path: other/install/. No artifacts will be uploaded.
          cd $HOME
          tar cvzf install.tgz other/install
          pwd
          ls -l

      - name: update build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chrono_build
          path: install.tgz
